# Generated by Django 6.0.1 on 2026-01-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardtransaction',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rewardtransaction',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
