# Generated by Django 4.2.7 on 2026-01-10 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('design_image', models.ImageField(upload_to='designs/')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='design_previews/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
