# Generated by Django 6.0.1 on 2026-01-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
