# Generated by Django 6.0.1 on 2026-01-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0003_design_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='preview_image',
        ),
        migrations.RemoveField(
            model_name='design',
            name='product',
        ),
    ]
