# Generated by Django 6.0.1 on 2026-01-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0004_remove_design_preview_image_remove_design_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='design_image',
        ),
        migrations.AddField(
            model_name='design',
            name='design_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='designs/'),
        ),
    ]
