# Generated by Django 6.0.1 on 2026-01-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0006_remove_design_design_data_design_custom_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
