# Generated by Django 4.2.7 on 2026-01-10 10:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintableArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('x_position', models.IntegerField(help_text='X coordinate of printable area')),
                ('y_position', models.IntegerField(help_text='Y coordinate of printable area')),
                ('width', models.IntegerField(help_text='Width of printable area in pixels')),
                ('height', models.IntegerField(help_text='Height of printable area in pixels')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printable_areas', to='products.product')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
