# Generated by Django 6.0.1 on 2026-01-13 14:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0005_remove_design_design_image_design_design_data_and_more'),
        ('products', '0005_product_is_featured_product_is_trending'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='designplacement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='designplacement',
            name='is_sale',
        ),
        migrations.RemoveField(
            model_name='designplacement',
            name='preview_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='designplacement',
            name='preview_mockup',
            field=models.ImageField(null=True, upload_to='mockups/'),
        ),
        migrations.AlterField(
            model_name='designplacement',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designs.design'),
        ),
        migrations.AlterField(
            model_name='designplacement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='printablearea',
            name='x',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='printablearea',
            name='y',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category'),
        ),
    ]
