# Generated by Django 6.0.1 on 2026-01-14 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0006_remove_design_design_data_design_custom_text_and_more'),
        ('products', '0006_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designplacement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='designplacement',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='designs.design'),
        ),
        migrations.AlterField(
            model_name='designplacement',
            name='layout_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designplacement',
            name='preview_mockup',
            field=models.ImageField(blank=True, null=True, upload_to='mockups/'),
        ),
        migrations.AlterField(
            model_name='designplacement',
            name='printable_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.printablearea'),
        ),
        migrations.AlterField(
            model_name='printablearea',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printablearea',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printablearea',
            name='x',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='printablearea',
            name='y',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
